-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 12:41:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema prodep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prodep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prodep` DEFAULT CHARACTER SET latin1 ;
USE `prodep` ;

-- -----------------------------------------------------
-- Table `prodep`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`administrador` (
  `adm_id` INT(11) NOT NULL AUTO_INCREMENT,
  `adm_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `adm_correo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`adm_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`areaeducativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`areaeducativa` (
  `are_id` INT(11) NOT NULL AUTO_INCREMENT,
  `are_nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`are_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`becario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`becario` (
  `bec_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bec_nombre` VARCHAR(70) NULL DEFAULT NULL,
  `bec_fechaInscripcion` VARCHAR(70) NULL DEFAULT NULL,
  `bec_correo` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`bec_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`convocatoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`convocatoria` (
  `con_id` INT(11) NOT NULL AUTO_INCREMENT,
  `con_nombre` VARCHAR(70) NULL DEFAULT NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`destinatario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`destinatario` (
  `des_id` INT(11) NOT NULL AUTO_INCREMENT,
  `des_nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`des_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`director` (
  `dir_id` INT(11) NOT NULL AUTO_INCREMENT,
  `dir_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `dir_correo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`dir_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`docente` (
  `doc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doc_numeroPersonal` INT(11) NULL DEFAULT NULL,
  `doc_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `doc_correo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`doc_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 155
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`entidadeducativa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`entidadeducativa` (
  `ent_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ent_nombre` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`ent_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`personal` (
  `per_id` INT(11) NOT NULL AUTO_INCREMENT,
  `per_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `per_correo` VARCHAR(50) NULL DEFAULT NULL,
  `per_rol` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`region` (
  `reg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `reg_nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`reg_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`proyecto` (
  `pro_id` INT(11) NOT NULL AUTO_INCREMENT,
  `pro_claveProgramtica` VARCHAR(50) NULL DEFAULT NULL,
  `pro_folioProdep` VARCHAR(50) NULL DEFAULT NULL,
  `pro_oficioAutorizacion` VARCHAR(50) NULL DEFAULT NULL,
  `pro_inicioApoyo` DATE NULL DEFAULT NULL,
  `pro_finApoyo` DATE NULL DEFAULT NULL,
  `pro_estado` TINYINT(1) NULL DEFAULT NULL,
  `pro_numeroDependencia` INT(11) NULL DEFAULT NULL,
  `doc_id` INT(11) NULL DEFAULT NULL,
  `adm_id` INT(11) NULL DEFAULT NULL,
  `dir_id` INT(11) NULL DEFAULT NULL,
  `ent_id` INT(11) NULL DEFAULT NULL,
  `per_id` INT(11) NULL DEFAULT NULL,
  `are_id` INT(11) NULL DEFAULT NULL,
  `reg_id` INT(11) NULL DEFAULT NULL,
  `con_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`pro_id`),
  INDEX `doc_id` (`doc_id` ASC),
  INDEX `adm_id` (`adm_id` ASC),
  INDEX `dir_id` (`dir_id` ASC),
  INDEX `ent_id` (`ent_id` ASC),
  INDEX `per_id` (`per_id` ASC),
  INDEX `are_id` (`are_id` ASC),
  INDEX `reg_id` (`reg_id` ASC),
  INDEX `con_id` (`con_id` ASC),
  CONSTRAINT `proyecto_ibfk_1`
    FOREIGN KEY (`doc_id`)
    REFERENCES `prodep`.`docente` (`doc_id`),
  CONSTRAINT `proyecto_ibfk_2`
    FOREIGN KEY (`adm_id`)
    REFERENCES `prodep`.`administrador` (`adm_id`),
  CONSTRAINT `proyecto_ibfk_3`
    FOREIGN KEY (`dir_id`)
    REFERENCES `prodep`.`director` (`dir_id`),
  CONSTRAINT `proyecto_ibfk_4`
    FOREIGN KEY (`ent_id`)
    REFERENCES `prodep`.`entidadeducativa` (`ent_id`),
  CONSTRAINT `proyecto_ibfk_5`
    FOREIGN KEY (`per_id`)
    REFERENCES `prodep`.`personal` (`per_id`),
  CONSTRAINT `proyecto_ibfk_6`
    FOREIGN KEY (`are_id`)
    REFERENCES `prodep`.`areaeducativa` (`are_id`),
  CONSTRAINT `proyecto_ibfk_7`
    FOREIGN KEY (`reg_id`)
    REFERENCES `prodep`.`region` (`reg_id`),
  CONSTRAINT `proyecto_ibfk_8`
    FOREIGN KEY (`con_id`)
    REFERENCES `prodep`.`convocatoria` (`con_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`registroconvocatoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`registroconvocatoria` (
  `reg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `reg_anoConvocatoria` DATE NULL DEFAULT NULL,
  `reg_estado` TINYINT(1) NULL DEFAULT NULL,
  `reg_fechaVoBo` DATE NULL DEFAULT NULL,
  `pro_id` INT(11) NULL DEFAULT NULL,
  `bec_id` INT(11) NULL DEFAULT NULL,
  `reg_fechaInicioBecario` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`reg_id`),
  INDEX `pro_id` (`pro_id` ASC),
  INDEX `bec_id` (`bec_id` ASC),
  CONSTRAINT `registroconvocatoria_ibfk_1`
    FOREIGN KEY (`pro_id`)
    REFERENCES `prodep`.`proyecto` (`pro_id`),
  CONSTRAINT `registroconvocatoria_ibfk_2`
    FOREIGN KEY (`bec_id`)
    REFERENCES `prodep`.`becario` (`bec_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`documento` (
  `doc_id` INT(11) NOT NULL AUTO_INCREMENT,
  `doc_nombre` VARCHAR(70) NULL DEFAULT NULL,
  `doc_estado` TINYINT(1) NULL DEFAULT NULL,
  `reg_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`doc_id`),
  INDEX `reg_id` (`reg_id` ASC),
  CONSTRAINT `documento_ibfk_1`
    FOREIGN KEY (`reg_id`)
    REFERENCES `prodep`.`registroconvocatoria` (`reg_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`oficio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`oficio` (
  `ofi_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ofi_numeroOficio` INT(11) NULL DEFAULT NULL,
  `ofi_anoConvocatoria` DATE NULL DEFAULT NULL,
  `ofi_folioProdep` VARCHAR(70) NULL DEFAULT NULL,
  `ofi_asunto` TEXT NULL DEFAULT NULL,
  `ofi_monto` VARCHAR(40) NULL DEFAULT NULL,
  `ofi_fechaEnvio` DATE NULL DEFAULT NULL,
  `ofi_fechaRespuesta` DATE NULL DEFAULT NULL,
  `ofi_aprobado` TINYINT(1) NULL DEFAULT NULL,
  `des_id` INT(11) NULL DEFAULT NULL,
  `con_id` INT(11) NULL DEFAULT NULL,
  `pro_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ofi_id`),
  INDEX `des_id` (`des_id` ASC),
  INDEX `con_id` (`con_id` ASC),
  INDEX `pro_id` (`pro_id` ASC),
  CONSTRAINT `oficio_ibfk_1`
    FOREIGN KEY (`des_id`)
    REFERENCES `prodep`.`destinatario` (`des_id`),
  CONSTRAINT `oficio_ibfk_2`
    FOREIGN KEY (`con_id`)
    REFERENCES `prodep`.`convocatoria` (`con_id`),
  CONSTRAINT `oficio_ibfk_3`
    FOREIGN KEY (`pro_id`)
    REFERENCES `prodep`.`proyecto` (`pro_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `prodep`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prodep`.`usuario` (
  `usu_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usu_nombre` VARCHAR(70) NULL DEFAULT NULL,
  `usu_contrasena` VARCHAR(70) NULL DEFAULT NULL,
  `per_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`usu_id`),
  INDEX `per_id` (`per_id` ASC),
  CONSTRAINT `usuario_ibfk_1`
    FOREIGN KEY (`per_id`)
    REFERENCES `prodep`.`personal` (`per_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;

USE `prodep` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
