use prodep;

insert into destinatario values(0,"gabriel morales diaz");
insert into destinatario values(0,"graciela hernandez sanchez");

insert into region values(0,"Xalapa");
insert into region values(0,"Veracruz");
insert into region values(0,"Poza Rica - Tuxpan");
insert into region values(0,"Orizaba - Cordoba");
insert into region values(0,"coatzacoalcos - Minatitlan");

insert into convocatoria values(0,"apoyos para estudios de posgrado de alta calidad");
insert into convocatoria values(0,"apoyo a la reincorporación de exbecarios promep");
insert into convocatoria values(0,"apoyo a la incorporación de nptc");
insert into convocatoria values(0,"apoyo a profesores con perfil deseable");
insert into convocatoria values(0,"reconocimiento a perfil deseable y apoyo");
	
insert into areaeducativa values(0,"Artes");
insert into areaeducativa values(0,"Biológico agropecuaria");
insert into areaeducativa values(0,"Ciencias de la salud");
insert into areaeducativa values(0,"Económico administrativa");
insert into areaeducativa values(0,"Humanidades");
insert into areaeducativa values(0,"Técnica");
insert into areaeducativa values(0,"UVI");

insert into entidadeducativa values(0,"centro de est., creacion y doc. de las artes");
insert into entidadeducativa values(0,"centro de idiomas");
insert into entidadeducativa values(0,"centro de idiomas y de autoacceso");
insert into entidadeducativa values(0,"centro de inv. en inteligencia artificial");
insert into entidadeducativa values(0,"centro de investigación e innovación en educación superior");
insert into entidadeducativa values(0,"centro de investigaciones cerebrales");
insert into entidadeducativa values(0,"centro de investigaciones tropicales");
insert into entidadeducativa values(0,"coordinacion academica reg. de enseñanza abierta");
insert into entidadeducativa values(0,"dir. gral. del area acad. de ciencias de la salud");
insert into entidadeducativa values(0,"escuela de enfermeria");
insert into entidadeducativa values(0,"escuela para estudiantes extranjeros");
insert into entidadeducativa values(0,"facultad de administracion");
insert into entidadeducativa values(0,"facultad de bioanalisis");
insert into entidadeducativa values(0,"facultad de biologia");
insert into entidadeducativa values(0,"facultad de ciencias administrativas y sociales");
insert into entidadeducativa values(0,"facultad de ciencias agricolas");
insert into entidadeducativa values(0,"facultad de ciencias biologicas y agropecuarias");
insert into entidadeducativa values(0,"facultad de ciencias biologico agropecuarias");
insert into entidadeducativa values(0,"facultad de ciencias quimicas");
insert into entidadeducativa values(0,"facultad de ciencias y tec. de la comunicacion");
insert into entidadeducativa values(0,"facultad de contaduria");
insert into entidadeducativa values(0,"facultad de contaduria y administracion");
insert into entidadeducativa values(0,"facultad de derecho");
insert into entidadeducativa values(0,"facultad de economia");
insert into entidadeducativa values(0,"facultad de enfermeria");
insert into entidadeducativa values(0,"facultad de estadistica e informatica");
insert into entidadeducativa values(0,"facultad de idiomas");
insert into entidadeducativa values(0,"facultad de ing. electronica y comunicaciones");
insert into entidadeducativa values(0,"facultad de ingenieria mecanica electrica");
insert into entidadeducativa values(0,"facultad de ingenieria");
insert into entidadeducativa values(0,"facultad de ingenieria civil");
insert into entidadeducativa values(0,"facultad de ingenieria mecanica y electrica");
insert into entidadeducativa values(0,"facultad de medicina");
insert into entidadeducativa values(0,"facultad de instrumentacion electronica");
insert into entidadeducativa values(0,"facultad de odontologia");
insert into entidadeducativa values(0,"facultad de medicina veterinaria y zootecnia");
insert into entidadeducativa values(0,"facultad de musica");
insert into entidadeducativa values(0,"facultad de pedagogia");
insert into entidadeducativa values(0,"facultad de quimica farmaceutica biologica");
insert into entidadeducativa values(0,"facultad de psicologia");
insert into entidadeducativa values(0,"ingenieria en sistemas de produccion agropecuaria");
insert into entidadeducativa values(0,"facultad de trabajo social");
insert into entidadeducativa values(0,"facultad de teatro");
insert into entidadeducativa values(0,"instituto de biotecnologia y ecologia aplicada");
insert into entidadeducativa values(0,"inst.de cs. marinas y pesquerias de la uv");
insert into entidadeducativa values(0,"instituto de ciencias de la salud");
insert into entidadeducativa values(0,"instituto de antropologia");
insert into entidadeducativa values(0,"instituto de ingenieria");
insert into entidadeducativa values(0,"instituto de investigaciones biologicas");
insert into entidadeducativa values(0,"instituto de invest. y estudios sup. eco. y soc.");
insert into entidadeducativa values(0,"instituto de investigaciones lingüistico lit.");
insert into entidadeducativa values(0,"instituto de investigaciones juridicas");
insert into entidadeducativa values(0,"instituto de investigaciones en educacion");
insert into entidadeducativa values(0,"instituto de salud publica");
insert into entidadeducativa values(0,"instituto de investigaciones psicologicas");
insert into entidadeducativa values(0,"instituto de neuroetologia");
insert into entidadeducativa values(0,"universidad veracruzana intercultural");
insert into entidadeducativa values(0,"museo de antropologia");
insert into entidadeducativa values(0,"unidad de serv. de apoyo resol.analitica (sara)");

insert into docente values(0,"36196","zarate betancourt eva","evzarate@uv.mx");
insert into docente values(0,"18392","zapien uscanga antonio de jesus","azapien@uv.mx");
insert into docente values(0,"30433","zapata lara helena del carmen","hzapata@uv.mx");
insert into docente values(0,"26303","villar sanchez patricia margarita","pvillar@uv.mx");
insert into docente values(0,"3004","vez lopez enrique","evez@uv.mx");
insert into docente values(0,"16056","verdejo lara rafael antonio","rverdejo@uv.mx");
insert into docente values(0,"45163","vazquez aguirre jorge luis","jorgevazquez02@uv.mx");
insert into docente values(0,"15084","varela cardoso miguel","mvarela@uv.mx");
insert into docente values(0,"23787","valenzuela orozco aura guadalupe","avalenzuela@uv.mx");
insert into docente values(0,"41781","torres sandoval imelda","imtorres@uv.mx");
insert into docente values(0,"15794","tello andrade adriana fabiola","ftello@uv.mx");
insert into docente values(0,"19864","solorzano hernandez rodolfo","rsolorzano@uv.mx");
insert into docente values(0,"28249","simbron barrera judith","jsimbron@uv.mx");
insert into docente values(0,"44844","silva ortega mariana","marsilva@uv.mx");
insert into docente values(0,"14487","silva aguilar oscar fernando","ossilva@uv.mx");
insert into docente values(0,"6089","sarmiento vega salvador ernesto","ssarmiento@uv.mx");
insert into docente values(0,"40614","santiago mijangos alma delia","alsantiago@uv.mx");
insert into docente values(0,"43658","sanchez alvarez guadalupe","guadalusanchez@uv.mx");
insert into docente values(0,"41306","sanchez garcia angel juan","angesanchez@uv.mx");
insert into docente values(0,"41380","salazar mendoza javier","jasalazar@uv.mx");
insert into docente values(0,"30080","salas garcia betzaida","besalas@uv.mx");
insert into docente values(0,"12986","salas benitez lazaro","lsalas@uv.mx");
insert into docente values(0,"31375","saiz calderon gomez manuel","msaizcalderon@uv.mx");
insert into docente values(0,"30872","ruz saldivar carlos","caruz@uv.mx");
insert into docente values(0,"24738","romero leon daniel arturo","daromero@uv.mx");
insert into docente values(0,"27376","rojas duran fausto","frojas@uv.mx");
insert into docente values(0,"19203","rodriguez flores carlos","carodriguez@uv.mx");
insert into docente values(0,"32501","roa gonzalez sheilla del carmen","sheillaroa@uv.mx");
insert into docente values(0,"32084","rivera krakowska octavio enrique","ocrivera@uv.mx");
insert into docente values(0,"25547","ricaño herrera francisco","fricano@uv.mx");
insert into docente values(0,"19430","rendon hernandez rogelio javier","rrendon@uv.mx");
insert into docente values(0,"31669","raya cruz blanca esther","braya@uv.mx");
insert into docente values(0,"5354","ramirez herrera daniel julian","daramirez@uv.mx");
insert into docente values(0,"9092","ramirez gonzalez luis david","dramirez@uv.mx");
insert into docente values(0,"35463","perez pastenes hugo","huperez@uv.mx");
insert into docente values(0,"36118","perez estrada laura celia","laperez@uv.mx");
insert into docente values(0,"32502","peñaflor fentanes estela","epenaflor@uv.mx");
insert into docente values(0,"41868","pech canche juan manuel","jmpech@uv.mx");
insert into docente values(0,"27315","pascual pineda luz alicia","lpascual@uv.mx");
insert into docente values(0,"37675","pascual mathey luz irene","lupascual@uv.mx");
insert into docente values(0,"35435","ortiz cruz fabiola","faortiz@uv.mx");
insert into docente values(0,"25683","ortega guerrero juan carlos","juaortega@uv.mx");
insert into docente values(0,"44362","ordaz hernandez monica berenice","mordaz@uv.mx");
insert into docente values(0,"4077","noriega riande francisco de jesus","fnoriega@uv.mx");
insert into docente values(0,"30609","nava vite rafael","rafnava@uv.mx");
insert into docente values(0,"25554","nahum lajud prisca","pnahum@uv.mx");
insert into docente values(0,"33803","molina roldan ahtziri erendira","ahmolina@uv.mx");
insert into docente values(0,"23117","molina hernandez jorge alberto","jmolina@uv.mx");
insert into docente values(0,"39925","martinez guevara gerson omar","germartinez@uv.mx");
insert into docente values(0,"37430","martinez sanchez cesar enrique","cesamartinez@uv.mx");
insert into docente values(0,"39754","martinez cabrera rosa arisbe","rosamartinez02@uv.mx");
insert into docente values(0,"2060","marquez montero sabino","smarquez@uv.mx");
insert into docente values(0,"27661","madrigal chavero erika paulina","emadrigal@uv.mx");
insert into docente values(0,"19886","lunagomez reyes roberto","rlunagomez@uv.mx");
insert into docente values(0,"30602","lopez gonzalez aime","ailopez@uv.mx");
insert into docente values(0,"42403","lopez gonzalez rocio","rociolopez@uv.mx");
insert into docente values(0,"13419","leal ortiz simon","sleal@uv.mx");
insert into docente values(0,"30576","lara ochoa ismael","ismlara@uv.mx");
insert into docente values(0,"32396","herrera melo jose arturo","arherrera@uv.mx");
insert into docente values(0,"15759","hernandez quiroz evaristo","evahernandez@uv.mx");
insert into docente values(0,"10016","hernandez ojeda humberto","huhernandez@uv.mx");
insert into docente values(0,"7391","hernandez lopez maria elvia","elvhernandez@uv.mx");
insert into docente values(0,"37937","hernandez contreras mariano azzur","marianohernandez@uv.mx");
insert into docente values(0,"27436","herbert vargas miguel angel allen","mherbert@uv.mx");
insert into docente values(0,"7146","gutierrez bonilla rosa ela","rosagutierrez@uv.mx");
insert into docente values(0,"4296","guiot vazquez maria isabel","iguiot@uv.mx");
insert into docente values(0,"18603","guillen ramirez susana anabel","sguillen@uv.mx");
insert into docente values(0,"27785","grappin navarro silvia ivette","sgrappin@uv.mx");
insert into docente values(0,"19789","gonzalez palmeros neli","negonzalez@uv.mx");
insert into docente values(0,"15845","gonzalez rosas monica karina","mogonzalez@uv.mx");
insert into docente values(0,"19049","gogeascoechea trejo maria del carmen","cgogeascoechea@uv.mx");
insert into docente values(0,"25250","gidi blanchet claudia elisa","cgidi@uv.mx");
insert into docente values(0,"31317","garcia valenzuela veronica","vegarcia@uv.mx");
insert into docente values(0,"34422","galindo monfil alma rosa","almgalindo@uv.mx");
insert into docente values(0,"38551","galan mendez frixia","fgalan@uv.mx");
insert into docente values(0,"40944","flores primo argel","argflores@uv.mx");
insert into docente values(0,"15660","flores badillo herlinda","hflores@uv.mx");
insert into docente values(0,"19904","figueroa vazquez lizette teresa","tfigueroa@uv.mx");
insert into docente values(0,"13821","fernandez figueroa jose antonio","antfernandez@uv.mx");
insert into docente values(0,"19306","fernandez arrazola zoila luz de los angeles","zfernandez@uv.mx");
insert into docente values(0,"33725","fernandez gomez imelda","imfernandez@uv.mx");
insert into docente values(0,"15352","enriquez corona rocio","renriquez@uv.mx");
insert into docente values(0,"26104","elorza martinez oralia","oelorza@uv.mx");
insert into docente values(0,"25274","diaz morales karina","kdiaz@uv.mx");
insert into docente values(0,"24801","diaz martinez jose vicente","vicdiaz@uv.mx");
insert into docente values(0,"6110","cruz juarez alma de los angeles","acruz@uv.mx");
insert into docente values(0,"15048","cruz capitaine roberto","robcruz@uv.mx");
insert into docente values(0,"15307","croche belin rene","rcroche@uv.mx");
insert into docente values(0,"29442","cortes sol albertina","alcortes@uv.mx");
insert into docente values(0,"10898","cocotle ronzon yolanda","ycocotle@uv.mx");
insert into docente values(0,"25566","chiquito contreras roberto gregorio","rchiquito@uv.mx");
insert into docente values(0,"28852","castillo morales marisol","maricastillo@uv.mx");
insert into docente values(0,"22640","carmona diaz gustavo","gcarmona@uv.mx");
insert into docente values(0,"36402","canales abarca adriana","acanales@uv.mx");
insert into docente values(0,"36529","camarillo montero jesus antonio","jcamarillo@uv.mx");
insert into docente values(0,"20727","bonilla hernandez nora maria","nbonilla@uv.mx");
insert into docente values(0,"43736","berdon carrasco victor hugo","viberdon@uv.mx");
insert into docente values(0,"32721","bello pineda javier","jabello@uv.mx");
insert into docente values(0,"42477","baronnet bruno jean james","bbaronnet@uv.mx ");
insert into docente values(0,"31436","badillo guzman jessica","jebadillo@uv.mx");
insert into docente values(0,"38269","arteaga vazquez mario alberto","maarteaga@uv.mx");
insert into docente values(0,"33105","arenzano altaif jesus antonio","jarenzano@uv.mx");
insert into docente values(0,"27928","alvarado olivarez mayvi","malvarado@uv.mx");
insert into docente values(0,"37705","altamirano vasquez margarita","maaltamirano@uv.mx");
insert into docente values(0,"7760","aldana franco rosario","raldana@uv.mx");
insert into docente values(0,"35357","alarcon zapata marco antonio","maralarcon@uv.mx");
insert into docente values(0,"31692","ahuja aguirre concepcion del carmen","cahuja@uv.mx");
insert into docente values(0,"14804","vazquez montano miriam laura","mivazquez@uv.mx");
insert into docente values(0,"24714","suarez dominguez emilio alfonso","emisuarez@uv.mx");
insert into docente values(0,"36744","rao vijendra dinesh","vrao@uv.mx");
insert into docente values(0,"44009","portillo velez rogelio de jesus","rportillo@uv.mx");
insert into docente values(0,"35482","perroni ventura yareni","yperroni@uv.mx");
insert into docente values(0,"34171","perez staples diana folger","diperez@uv.mx  ");
insert into docente values(0,"35478","morales zarate epifanio","epmorales@uv.mx");
insert into docente values(0,"39440","mondragon vasquez karina","kmondragon@uv.mx");
insert into docente values(0,"34261","mac swiney gonzalez maria cristina","cmacswiney@uv.mx");
insert into docente values(0,"35016","lopez acosta juan carlos","carlolopez@uv.mx");
insert into docente values(0,"32643","kromer thorsten","tkromer@uv.mx");
insert into docente values(0,"32457","huerta gonzalez sara","sahuerta@uv.mx");
insert into docente values(0,"13734","hernandez suarez jesus","jeshernandez@uv.mx");
insert into docente values(0,"39436","hernandez escobedo quetzalcoatl cruz","qhernandez@uv.mx");
insert into docente values(0,"30559","diaz fleischer francisco","fradiaz@uv.mx");
insert into docente values(0,"40939","cruz cruz carlos alberto","calcruz@uv.mx");
insert into docente values(0,"19244","canales rubio miguel","mcanales@uv.mx");
insert into docente values(0,"43111","baena hurtado martha lucia","mbaena@uv.mx");
insert into docente values(0,"83","alvarez montero jose lorenzo","lalvarez@uv.mx");
insert into docente values(0,"45468","serna lagunes ricardo","rserna@uv.mx");
insert into docente values(0,"29883","sangabriel conde wendy","wsangabriel@uv.mx");
insert into docente values(0,"41474","sanchez menendez juan emilio","jsanchez@uv.mx");
insert into docente values(0,"46568","rosas santiago francisco javier","frrosas@uv.mx");
insert into docente values(0,"23173","rechy ramirez ericka janet","erechy@uv.mx");
insert into docente values(0,"47333","pinos rodriguez juan manuel","jpinos@uv.mx");
insert into docente values(0,"36757","ortiz chacha christian soledad","chortiz@uv.mx");
insert into docente values(0,"28650","ocharan hernandez jorge octavio","jocharan@uv.mx");
insert into docente values(0,"22619","naval avila celina","cnaval@uv.mx");
insert into docente values(0,"39604","montane jimenez luis gerardo","lmontane@uv.mx");
insert into docente values(0,"21068","mendez ortiz jesus roberto","jmendez@uv.mx");
insert into docente values(0,"43895","lopez huerta francisco","frlopez@uv.mx");
insert into docente values(0,"17585","lagunes merino omar","olagunes@uv.mx");
insert into docente values(0,"45200","jordan garza adan guillermo","ajordan@uv.mx");
insert into docente values(0,"43161","herrera covarrubias deissy","deherrera@uv.mx");
insert into docente values(0,"41133","chagoya fuentes jorge luis","jochagoya@uv.mx");
insert into docente values(0,"32192","castillo hernandez estela","estelcastillo@uv.mx");
insert into docente values(0,"48542","canul chan michel de la cruz","mcanul@uv.mx");
insert into docente values(0,"34390","barradas hernandez jose eriban","erbarradas@uv.mx");
insert into docente values(0,"44633","andres meza pablo","pandres@uv.mx");
insert into docente values(0,"47463","allende molar raul","raallende@uv.mx");
insert into docente values(0,"47737","aguilar justo marving omar","marvaguilar@uv.mx");
insert into docente values(0,"37686","villagran villegas luz yazmin","yvillagran@uv.mx");
insert into docente values(0,"34511","suarez franco jose luis","jsuarez@uv.mx");
insert into docente values(0,"34771","landa rivera ruth angelica","rulanda@uv.mx");
insert into docente values(0,"23353","velasco ramirez maria luisa","lvelasco@uv.mx");
insert into docente values(0,"36811","lopez lara rocio","rociolopez02@uv.mx");
insert into docente values(0,"44397","infante pacheco victor eduardo","vinfante@uv.mx");

insert into director values (0,"dra. lourdes budar jiménez","lbudar@uv.mx");
insert into director values (0,"dra. clara luz parra uscanga","cparra@uv.mx");
insert into director values (0,"dra. ma teresa de la luz sainz barajas","tsainz@uv.mx");
insert into director values (0,"dra. leidy margarita lópez castro,","leilopez@uv.mx");
insert into director values (0,"mtra. carmen báez velázquez","cabaez@uv.mx");
insert into director values (0,"dr. otto raúl leyva ovalle","oleyva@uv.mx");
insert into director values (0,"dr. pablo samuel luna lozano","paluna@uv.mx");
insert into director values (0,"dra. maribel domínguez basurto","madominguez@uv.mx");
insert into director values (0,"dr. eduardo castillo gonzález","educastillo@uv.mx");
insert into director values (0,"mtro. miguel ángel cruz treviño","migcruz@uv.mx");
insert into director values (0,"dr. enrique a. morales gonzález","emorales@uv.mx");
insert into director values (0,"ing. hugo i. noble pérez","hnoble@uv.mx");
insert into director values (0,"mtro. cecilio juárez osorio","cjuarez@uv.mx");
insert into director values (0,"m.e. gabriela pucheta xolo2","gapucheta@uv.mx");
insert into director values (0,"mtra. maría antonia aguilar pérez","antoaguilar@uv.mx");
insert into director values (0,"m.c.c. carlos alberto ochoa rivera","cochoa@uv.mx");
insert into director values (0,"mtra.  maria esperanza conzatti hernández","econzatti@uv.mx");
insert into director values (0,"ma. gabriela nachón garcía","gnachon@uv.mx");
insert into director values (0,"mtra. edalid álvarez velázquez","edalvarez@uv.mx");
insert into director values (0,"dr. julio cesar viñas dozal","jvinas@uv.mx");
insert into director values (0,"mtro. miguel sosa ruíz","msosa@uv.mx");
insert into director values (0,"dr. darío f. hernández gonzález","darhernandez@uv.mx");
insert into director values (0,"dr. jorge manzo denes","jmanzo@uv.mx");
insert into director values (0,"m. c. miguel ángel rojas hernández","mrojas@uv.mx");
insert into director values (0,"mtro. nerio gonzález morales.","nergonzalez@uv.mx");
insert into director values (0,"dr. jorge alberto vélez enríquez","jvelez@uv.mx");
insert into director values (0,"dr. arturo bocardo valle","abocardo@uv.mx");
insert into director values (0,"dr. arturo serrano solis","arserrano@uv.mx");
insert into director values (0,"m.c. luis alberto sánchez bazán","luisasanchez@uv.mx");
insert into director values (0,"mtro. gabriel zarate flores","gzarate@uv.mx");
insert into director values (0,"dr. alejandro de la fuente alonso","adelafuente@uv.mx");
insert into director values (0,"dra. maribel vázquez hernández","marivazquez@uv.mx");
insert into director values (0,"dr. eduardo rivadeneyra domínguez","edrivadeneyra@uv.mx");
insert into director values (0,"dr. juan antonio castañeda felgueroso","acastaneda@uv.mx");
insert into director values (0,"dr. juan carlos ortega guerrero","juaortega@uv.mx");
insert into director values (0,"dra. maría eugenia senties santos","esenties@uv.mx");
insert into director values (0,"dra. martha patricia domínguez chenge","martdominguez@uv.mx");
insert into director values (0,"dra. ahtziri e. molina roldán","ahmolina@uv.mx");
insert into director values (0,"dra. maría de los ángeles morales sosa","amorales@uv.mx");
insert into director values (0,"m.i.a. martín augusto pérez panes","augperez@uv.mx");
insert into director values (0,"mtra. julieta varanasi gonzález garcía","juligonzalez@uv.mx");
insert into director values (0,"dra. maura ordoñez valenzuela","mordonez@uv.mx");
insert into director values (0,"mtro. evaristo hernández quiroz","evahernandez@uv.mx");
insert into director values (0,"mtro. juan grapain contreras","jgrapain@uv.mx");
insert into director values (0,"m.a. andrea francisca ortiz muñoz","fortiz@uv.mx");
insert into director values (0,"r. ángel fernández arriola","afernandez@uv.mx");
insert into director values (0,"dr. jerónimo ricárdez jiménez","jricardez@uv.mx");
insert into director values (0,"dra. irma liliana domínguez cañedo","irdominguez@uv.mx");
insert into director values (0,"dr. jorge genaro vicente martínez","jvicente@uv.mx");
insert into director values (0,"mtro. antonio iván sánchez huerta","antonsanchez@uv.mx");
insert into director values (0,"m.c.  nayib bechara acar martínez","nacar@uv.mx");
insert into director values (0,"mtra. irma josefina jácome sánchez","ijacome@uv.mx");
insert into director values (0,"dr. pedro gutiérrez  aguilar","pgutierrez@uv.mx");
insert into director values (0,"ra. clementina barrera bernal","cbarrera@uv.mx");
insert into director values (0,"dr. andrés rivera fernández","arivera@uv.mx");
insert into director values (0,"dra. rosy lorena laurencio meza","rlaurencio@uv.mx");
insert into director values (0,"dr. javier bello pineda","jabello@uv.mx");
insert into director values (0,"dra. gloria elena sánchez cruz","gcruz@uv.mxg");
insert into director values (0,"dr. juan carlos noa carrazana","jnoa@uv.mx");
insert into director values (0,"dr. jorge e.  morales mávil","jormorales@uv.mxj");
insert into director values (0,"dra. shantal meseguer galván","smeseguer@uv.mx");
insert into director values (0,"lic. francisco velázquez sarmiento","frvelazquez@uv.mx");
insert into director values (0,"dr. alfonso alexander aguilera","aalexander@uv.mx");
insert into director values (0,"dra. rosaura citlalli lópez binnqüist","cilopez@uv.mx");
insert into director values (0,"mtra. iracema ramos aguilar","irramos@uv.mx");
insert into director values (0,"m. en c. alvar gonzález christen","agonzalez@uv.mx");
insert into director values (0,"mtra. celia cristina contreras asturias","celcontreras@uv.mx");
insert into director values (0,"msp. edit rodríguez romero","edrodriguez@uv");
insert into director values (0,"dra. sandra luz gonzález herrera","sgonzalez@uv.mx");
insert into director values (0,"dra. ma. estela montes carmona","emontes@uv.mx");
insert into director values (0,"dr. juan rodrigo laguna camacho","jlaguna@uv.mx");
insert into director values (0,"joaquín romero ricavar","joaquromero@uv.mx");
insert into director values (0,"dr. carlos flores pérez","carlflores@uv.mx");

insert into administrador values(0,"lic. alejandra durán tovilla","aleduran@uv.mx");
insert into administrador values(0,"l.a.e. solveig hernández nieto","solhernandez@uv.mx");
insert into administrador values(0,"l.a.e. edgar pérez fuentes","edperez@uv.mx");
insert into administrador values(0,"lic. rafael gonzález delgado","rafaelgonzalez@uv.mx");
insert into administrador values(0,"lic. gabriela maria austria pineda","gaustria@uv.mx");
insert into administrador values(0,"ruiz ramon deysi edith","deruiz@uv.mx");
insert into administrador values(0,"lc bulfrano orea hernández","borea@uv.mx");
insert into administrador values(0,"mtra. nelly del carmen rodríguez pérez","nelrodriguez@uv.mx");
insert into administrador values(0,"francisco  lendechy león","flendechy@uv.mx");
insert into administrador values(0,"ing. maría del rosario cabrera lara","rcabrera@uv.mx");
insert into administrador values(0,"lic. vanessa verónica medina muñoz","vmedina@uv.mx");
insert into administrador values(0,"lic. héctor antonio murrieta rivera","hmurrieta@uv.mx");
insert into administrador values(0,"lic. omar elias sarmiento quezada","osarmiento@uv.mx");
insert into administrador values(0,"c.p. alfredo grande roy","agrande@uv.mx");
insert into administrador values(0,"lic. patricia contreras pérez","patcontreras@uv.mx");
insert into administrador values(0,"l.r.i. josé ángel garcía ronzón","angelgarcia1@uv.mx");
insert into administrador values(0,"l.a.e. maximiliano ornelas reyes","mornelas@uv.mx");
insert into administrador values(0,"c.p. rubicelia martínez hernández","rumartinez@uv.mx");
insert into administrador values(0,"lic. erika nathalie aguilar acevedo","eriaguilar@uv.mx");
insert into administrador values(0,"lic. cándida yazmín gómez candanedo","cangomez@uv.mx");
insert into administrador values(0,"lic. jesús tedy guerrero","jetedy@uv.mx");
insert into administrador values(0,"lae. adriana aburto núñez","adaburto@uv.mx");
insert into administrador values(0,"c.p. isaura santa hernández martínez","ihernandez@uv.mx");
insert into administrador values(0,"lic. samantha sofía ferez ramos","sferez@uv.mx");
insert into administrador values(0,"c.p. flor haydee gutierrez bermudes","flgutierrez@uv.mx");
insert into administrador values(0,"c.p. germán vázquez hernández","gvazquez@uv.mx");
insert into administrador values(0,"castañeda rosas alma delia","alcastaneda@uv.mx");
insert into administrador values(0,"c.p. obdulia carreto caraza","ocarreto@uv.mx");
insert into administrador values(0,"lae. hernán hernández rivera","herhernandez@uv.mx");
insert into administrador values(0,"lic. diana cortez hernández","dcortez@uv.mx");
insert into administrador values(0,"c.p. silvia croda lagunes","scroda@uv.mx");
insert into administrador values(0,"l.r.i. tania iveth ramírez velázquez","taramirez@uv.mx");
insert into administrador values(0,"mtra. analidia luján gutiérrez","alujan@uv.mx");
insert into administrador values(0,"vargas prieto gladys","glvargas@uv.mx");
insert into administrador values(0,"mtra. teresa vianey sánchez lara","tesanchez@uv.mx");
insert into administrador values(0,"c.p. martha cabrera jiménez","macabrera@uv.mx");
insert into administrador values(0,"lic. ana elena hernández ponce","elehernandez@uv.mx");
insert into administrador values(0,"mtra. laura arellano pratz","larellano@uv.mx");
insert into administrador values(0,"sácnite fabiola valera velasco","savalera@uv.mx");
insert into administrador values(0,"beatriz suárez rivera","bsuarez@uv.mx");
insert into administrador values(0,"lae francisco salazar pimentel","fsalazar@uv.mx");
insert into administrador values(0,"lae yadira sarmiento mora","ysarmiento@uv.mx");
insert into administrador values(0,"mca. verónica martínez ramos","vermartinez@uv.mx");
insert into administrador values(0,"m.v.z. victor hugo garcía sánchez","vgarcia@uv.mx");
insert into administrador values(0,"mtra. irma josefina jácome sánchez","ijacome@uv.mx");
insert into administrador values(0,"c. ana edith méndez ramírez","anamendez@uv.mx");
insert into administrador values(0,"lic. manuel adan rodriguez rivera","manrodriguez@uv.mx");
insert into administrador values(0,"lic. maría guadalupe robles campos","grobles@uv.mx");
insert into administrador values(0,"c.p. anais b. arango garcía","anarango@uv.mx");
insert into administrador values(0,"lic. miguel ángel salazar rodríguez","jabello@uv.mx");
insert into administrador values(0,"liliana lópez montiel","lillopez@uv.mx");
insert into administrador values(0,"mtro. josé rafael mejía olivo","rafmejia@uv.mx");
insert into administrador values(0,"cp angelina molina","angmolina@uv.mx");
insert into administrador values(0,"lc norma mendoza lópez","nmendoza@uv.mx");
insert into administrador values(0,"lic. marco antonio aguirre cortez","antaguirre@uv.mx");
insert into administrador values(0,"c.p. maría del carmen valdez juárez","cvaldez@uv.mx");
insert into administrador values(0,"l.a. barbara maría lópez ríos","balopez@uv.mx");
insert into administrador values(0,"lic. rosalía petrone san filippo","rpetrone@uv.mx");
insert into administrador values(0,"c.p. gloria esther ortiz guzmán","glortiz@uv.mx");
insert into administrador values(0,"mtra. nayeli rodríguez pimentel","narodriguez@uv.mx");
insert into administrador values(0,"c.p. angélica tapia vázquez","isp@uv.mx. ");
insert into administrador values(0,"reyes lopez leticia","lreyes@uv.mx");
insert into administrador values(0,"rodriguez diaz manuel alejandro","alejandrorodriguez@uv.mx");